import { toIndex } from './board';
import { wallSpecToBoard, type WallSpec } from './wallSpec';
import type { PuzzleState } from './types';

export const fixedUserWallSpec = {
  size: 16,
  outerWalls: true,
  centerBlock: [
    [7, 7],
    [8, 7],
    [7, 8],
    [8, 8],
  ],
  vWalls: [
    [5, 0],
    [10, 0],
    [2, 1],
    [14, 1],
    [6, 3],
    [9, 3],
    [5, 5],
    [1, 6],
    [11, 6],
    [14, 6],
    [7, 7],
    [9, 7],
    [5, 8],
    [7, 8],
    [9, 8],
    [12, 8],
    [10, 9],
    [10, 11],
    [5, 13],
    [2, 14],
    [14, 14],
    [6, 15],
    [11, 15],
  ],
  hWalls: [
    [2, 1],
    [13, 1],
    [9, 3],
    [6, 4],
    [0, 5],
    [4, 5],
    [1, 7],
    [7, 7],
    [8, 7],
    [10, 7],
    [14, 7],
    [12, 8],
    [5, 9],
    [7, 9],
    [8, 9],
    [10, 10],
    [15, 11],
    [0, 12],
    [9, 12],
    [15, 12],
    [4, 13],
    [14, 14],
    [1, 15],
  ],
  targets: [
    { x: 2, y: 1, color: 'yellow', shape: 'circle' },
    { x: 13, y: 1, color: 'green', shape: 'triangle' },
    { x: 6, y: 3, color: 'blue', shape: 'triangle' },
    { x: 9, y: 3, color: 'red', shape: 'circle' },
    { x: 4, y: 5, color: 'red', shape: 'square' },
    { x: 1, y: 6, color: 'green', shape: 'cross' },
    { x: 10, y: 6, color: 'blue', shape: 'square' },
    { x: 14, y: 6, color: 'yellow', shape: 'cross' },
    { x: 5, y: 8, color: 'yellow', shape: 'square' },
    { x: 12, y: 8, color: 'rainbow', shape: 'vortex' },
    { x: 2, y: 9, color: 'green', shape: 'circle' },
    { x: 10, y: 9, color: 'blue', shape: 'circle' },
    { x: 9, y: 11, color: 'yellow', shape: 'triangle' },
    { x: 15, y: 12, color: 'green', shape: 'square' },
    { x: 4, y: 13, color: 'blue', shape: 'cross' },
    { x: 1, y: 14, color: 'red', shape: 'triangle' },
    { x: 14, y: 14, color: 'red', shape: 'cross' },
  ],
} satisfies WallSpec;

export const fixedUserBoard = wallSpecToBoard(fixedUserWallSpec);

export const fixedUserPuzzle: PuzzleState = {
  robots: {
    red: toIndex(13, 8, fixedUserBoard),
    blue: toIndex(13, 6, fixedUserBoard),
    yellow: toIndex(1, 5, fixedUserBoard),
    green: toIndex(6, 12, fixedUserBoard),
    black: toIndex(15, 15, fixedUserBoard),
  },
  targetRobot: 'yellow',
  targetCell: toIndex(1, 2, fixedUserBoard),
};
